### PR TITLE
Feature/cu hk6f9y combat script

### PR DESCRIPTION
**Pull request by Yonimevicio**
imagen
imagen

### CODE REVIEW

**Review by telmiuse — CHANGES_REQUESTED** [review]
Meta problems with timestamp and ids

**Review by JaimeBea — APPROVED** [review]

**Review by FrancPS — APPROVED** [review]
I cannot load Telmooo scene, therefore i'd have to build everything to test it.

Seems that the scene is broken and crashes in multiple places when trying to Load. Even being an unnecessary scene, check if this might have an impact in the engine somehow.

Check if the animations and controls work fine in GAME. (Do this test after any changes requested by the reviewers.)

The rest seems fine, nice code!

**Review by telmiuse — APPROVED** [review]

**Comment by Yonimevicio** [comment]
> 
> 
> I cannot load Telmooo scene, therefore i'd have to build everything to test it.
> 
> Seems that the scene is broken and crashes in multiple places when trying to Load. Even being an unnecessary scene, check if this might have an impact in the engine somehow.
> 
> Check if the animations and controls work fine in GAME. (Do this test after any changes requested by the reviewers.)
> 
> The rest seems fine, nice code!

i deleted telmo scene it was not used at all

**Review by Jordi-Gil — APPROVED** [review]

**Review by GBMiro — APPROVED** [review]

**Review by Jordi-Gil — CHANGES_REQUESTED** [review]
Blocked, by other PR

**Pull request closed without merging**
